### ISSUE TITLE
Bug - Unable to Change Workout Type

### ISSUE THREAD

**Issue by tun82434** [cis3296s24/01-Gains-AI#20]
I clicked 'Get Started' to start a workout. I chose meditation and filled in the form and hit submit. In meditation, it seemed like it would not generate any workouts. Clicking on change workout type also did not work, it sent me to a URL that does not exist.

**Comment by tuo65794** [comment]
Thank you for the feedback,  Fixed change workout. Meditation form worked but would check on the outputs
